In [1]:
import tushare as ts
import pandas as pd
import datetime, time
import sqlite3
import sqlite_data
import time

In [2]:
pro = ts.pro_api()

In [3]:
from sqlite_data import DataApi
data_api = DataApi()

In [5]:
pro.stock_mx(trade_date='20221109')

     trade_date    ts_code  mx_grade  com_stock      evd_v  zt_sum_z  wma250_z
0      20221109  000001.SZ         4  -0.863925  48.854036 -1.185493 -1.118567
1      20221109  000002.SZ         4  -1.365085  47.145826 -2.215437 -1.064376
2      20221109  000004.SZ         3   0.300791  52.185379  0.494164 -0.403391
3      20221109  000005.SZ         4  -0.063896  50.123635  0.163407 -0.182648
4      20221109  000006.SZ         3  -0.875240  47.831841 -0.802834 -0.434269
...         ...        ...       ...        ...        ...       ...       ...
4961       None       None         2   0.057803        NaN  0.265242  0.323662
4962       None       None         2  -0.192359        NaN       NaN  0.118825
4963   20221109  900937.SH         1   0.485199  49.591884  0.778773  0.948965
4964   20221109  900946.SH         3  -0.276342  49.354156 -0.000068 -0.229694
4965       None       None         2   0.053111        NaN  0.189990  0.325901

[4966 rows x 7 columns]

In [4]:
trade_cal = pd.DataFrame(data_api.trade_cal(exchange='SSE', is_open='1', fields=['cal_date'])['cal_date'][::-1])

In [5]:
trade_cal

      cal_date
8069  19901219
8068  19901220
8067  19901221
8066  19901224
8065  19901225
...        ...
4     20231225
3     20231226
2     20231227
1     20231228
0     20231229

[8070 rows x 1 columns]

In [15]:
trade_cal['week_info'] = trade_cal.apply(lambda x: datetime.datetime.strptime(x['cal_date'], '%Y%m%d').date().isocalendar(), axis=1)
trade_cal['year'] = trade_cal.apply(lambda x: x['week_info'][0], axis=1)
trade_cal['week'] = trade_cal.apply(lambda x: x['week_info'][1], axis=1)
trade_cal['day'] = trade_cal.apply(lambda x: x['week_info'][2], axis=1)

      cal_date      week_info  year  week  day
8069  19901219  (1990, 51, 3)  1990    51    3
8068  19901220  (1990, 51, 4)  1990    51    4
8067  19901221  (1990, 51, 5)  1990    51    5
8066  19901224  (1990, 52, 1)  1990    52    1
8065  19901225  (1990, 52, 2)  1990    52    2
...        ...            ...   ...   ...  ...
4     20231225  (2023, 52, 1)  2023    52    1
3     20231226  (2023, 52, 2)  2023    52    2
2     20231227  (2023, 52, 3)  2023    52    3
1     20231228  (2023, 52, 4)  2023    52    4
0     20231229  (2023, 52, 5)  2023    52    5

[8070 rows x 5 columns]

In [36]:
df = trade_cal.groupby(['year','week']).apply(lambda x: x[x['day']==x['day'].max()])

In [40]:
df

                cal_date      week_info  year  week  day
year week
1990 51   8067  19901221  (1990, 51, 5)  1990    51    5
     52   8062  19901228  (1990, 52, 5)  1990    52    5
1991 1    8058  19910104   (1991, 1, 5)  1991     1    5
     2    8053  19910111   (1991, 2, 5)  1991     2    5
     3    8048  19910118   (1991, 3, 5)  1991     3    5
...                  ...            ...   ...   ...  ...
2023 48   20    20231201  (2023, 48, 5)  2023    48    5
     49   15    20231208  (2023, 49, 5)  2023    49    5
     50   10    20231215  (2023, 50, 5)  2023    50    5
     51   5     20231222  (2023, 51, 5)  2023    51    5
     52   0     20231229  (2023, 52, 5)  2023    52    5

[1675 rows x 5 columns]

In [42]:
df2 = list(df['cal_date'])

In [43]:
df2

['19901221',
 '19901228',
 '19910104',
 '19910111',
 '19910118',
 '19910125',
 '19910201',
 '19910208',
 '19910214',
 '19910222',
 '19910301',
 '19910308',
 '19910315',
 '19910322',
 '19910329',
 '19910405',
 '19910412',
 '19910419',
 '19910426',
 '19910503',
 '19910510',
 '19910517',
 '19910524',
 '19910531',
 '19910607',
 '19910614',
 '19910621',
 '19910628',
 '19910705',
 '19910712',
 '19910719',
 '19910726',
 '19910802',
 '19910809',
 '19910816',
 '19910823',
 '19910830',
 '19910906',
 '19910913',
 '19910920',
 '19910927',
 '19911004',
 '19911011',
 '19911018',
 '19911025',
 '19911101',
 '19911108',
 '19911115',
 '19911122',
 '19911129',
 '19911206',
 '19911213',
 '19911220',
 '19911227',
 '19920103',
 '19920110',
 '19920117',
 '19920124',
 '19920131',
 '19920207',
 '19920214',
 '19920221',
 '19920228',
 '19920306',
 '19920313',
 '19920320',
 '19920327',
 '19920403',
 '19920410',
 '19920417',
 '19920424',
 '19920430',
 '19920508',
 '19920515',
 '19920522',
 '19920529',
 '19920605',
 '19920612',
 '19920619',
 '19920626',
 '19920703',
 '19920710',
 '19920717',
 '19920724',
 '19920731',
 '19920807',
 '19920814',
 '19920821',
 '19920828',
 '19920904',
 '19920911',
 '19920918',
 '19920925',
 '19920930',
 '19921009',
 '19921016',
 '19921023',
 '19921030',
 '19921106',
 '19921113',
 '19921120',
 '19921127',
 '19921204',
 '19921211',
 '19921218',
 '19921225',
 '19921231',
 '19930108',
 '19930115',
 '19930122',
 '19930129',
 '19930205',
 '19930212',
 '19930219',
 '19930226',
 '19930305',
 '19930312',
 '19930319',
 '19930326',
 '19930402',
 '19930409',
 '19930416',
 '19930423',
 '19930430',
 '19930507',
 '19930514',
 '19930521',
 '19930528',
 '19930604',
 '19930611',
 '19930618',
 '19930625',
 '19930702',
 '19930709',
 '19930716',
 '19930723',
 '19930730',
 '19930806',
 '19930813',
 '19930820',
 '19930827',
 '19930903',
 '19930910',
 '19930917',
 '19930924',
 '19930930',
 '19931008',
 '19931015',
 '19931022',
 '19931029',
 '19931105',
 '19931112',
 '19931119',
 '19931126',
 '19931203',
 '19931210',
 '19931217',
 '19931224',
 '19931231',
 '19940107',
 '19940114',
 '19940121',
 '19940128',
 '19940204',
 '19940218',
 '19940225',
 '19940304',
 '19940311',
 '19940318',
 '19940325',
 '19940401',
 '19940408',
 '19940415',
 '19940422',
 '19940429',
 '19940506',
 '19940513',
 '19940520',
 '19940527',
 '19940603',
 '19940610',
 '19940617',
 '19940624',
 '19940701',
 '19940708',
 '19940715',
 '19940722',
 '19940729',
 '19940805',
 '19940812',
 '19940819',
 '19940826',
 '19940902',
 '19940909',
 '19940916',
 '19940923',
 '19940930',
 '19941007',
 '19941014',
 '19941021',
 '19941028',
 '19941104',
 '19941111',
 '19941118',
 '19941125',
 '19941202',
 '19941209',
 '19941216',
 '19941223',
 '19941230',
 '19950106',
 '19950113',
 '19950120',
 '19950127',
 '19950210',
 '19950217',
 '19950224',
 '19950303',
 '19950310',
 '19950317',
 '19950324',
 '19950331',
 '19950407',
 '19950414',
 '19950421',
 '19950428',
 '19950505',
 '19950512',
 '19950519',
 '19950526',
 '19950602',
 '19950609',
 '19950616',
 '19950623',
 '19950630',
 '19950707',
 '19950714',
 '19950721',
 '19950728',
 '19950804',
 '19950811',
 '19950818',
 '19950825',
 '19950901',
 '19950908',
 '19950915',
 '19950922',
 '19950929',
 '19951006',
 '19951013',
 '19951020',
 '19951027',
 '19951103',
 '19951110',
 '19951117',
 '19951124',
 '19951201',
 '19951208',
 '19951215',
 '19951222',
 '19951229',
 '19960105',
 '19960112',
 '19960119',
 '19960126',
 '19960202',
 '19960209',
 '19960216',
 '19960308',
 '19960315',
 '19960322',
 '19960329',
 '19960405',
 '19960412',
 '19960419',
 '19960426',
 '19960503',
 '19960510',
 '19960517',
 '19960524',
 '19960531',
 '19960607',
 '19960614',
 '19960621',
 '19960628',
 '19960705',
 '19960712',
 '19960719',
 '19960726',
 '19960802',
 '19960809',
 '19960816',
 '19960823',
 '19960830',
 '19960906',
 '19960913',
 '19960920',
 '19960927',
 '19961004',
 '19961011',
 '19961018',
 '19961025',
 '19961101',
 '19961108',
 '19961115',
 '19961122',
 '19961129',
 '19961206',
 '19961213',
 '19961220',
 '19961227',
 '19970103',
 '19970110',
 '19970117',
 '19970124',
 '19970131',
 '19970221',
 '19970228',
 '19970307',
 '19970314',
 '19970321',
 '19970328',
 '19970404',
 '19970411',
 '19970418',
 '19970425',
 '19970430',
 '19970509',
 '19970516',
 '19970523',
 '19970530',
 '19970606',
 '19970613',
 '19970620',
 '19970627',
 '19970704',
 '19970711',
 '19970718',
 '19970725',
 '19970801',
 '19970808',
 '19970815',
 '19970822',
 '19970829',
 '19970905',
 '19970912',
 '19970919',
 '19970926',
 '19970930',
 '19971010',
 '19971017',
 '19971024',
 '19971031',
 '19971107',
 '19971114',
 '19971121',
 '19971128',
 '19971205',
 '19971212',
 '19971219',
 '19971226',
 '19971231',
 '19980109',
 '19980116',
 '19980123',
 '19980213',
 '19980220',
 '19980227',
 '19980306',
 '19980313',
 '19980320',
 '19980327',
 '19980403',
 '19980410',
 '19980417',
 '19980424',
 '19980430',
 '19980508',
 '19980515',
 '19980522',
 '19980529',
 '19980605',
 '19980612',
 '19980619',
 '19980626',
 '19980703',
 '19980710',
 '19980717',
 '19980724',
 '19980731',
 '19980807',
 '19980814',
 '19980821',
 '19980828',
 '19980904',
 '19980911',
 '19980918',
 '19980925',
 '19980930',
 '19981009',
 '19981016',
 '19981023',
 '19981030',
 '19981106',
 '19981113',
 '19981120',
 '19981127',
 '19981204',
 '19981211',
 '19981218',
 '19981225',
 '19981231',
 '19990108',
 '19990115',
 '19990122',
 '19990129',
 '19990205',
 '19990209',
 '19990305',
 '19990312',
 '19990319',
 '19990326',
 '19990402',
 '19990409',
 '19990416',
 '19990423',
 '19990430',
 '19990507',
 '19990514',
 '19990521',
 '19990528',
 '19990604',
 '19990611',
 '19990618',
 '19990625',
 '19990702',
 '19990709',
 '19990716',
 '19990723',
 '19990730',
 '19990806',
 '19990813',
 '19990820',
 '19990827',
 '19990903',
 '19990910',
 '19990917',
 '19990924',
 '19990930',
 '19991008',
 '19991015',
 '19991022',
 '19991029',
 '19991105',
 '19991112',
 '19991119',
 '19991126',
 '19991203',
 '19991210',
 '19991217',
 '19991224',
 '19991230',
 '20000107',
 '20000114',
 '20000121',
 '20000128',
 '20000218',
 '20000225',
 '20000303',
 '20000310',
 '20000317',
 '20000324',
 '20000331',
 '20000407',
 '20000414',
 '20000421',
 '20000428',
 '20000512',
 '20000519',
 '20000526',
 '20000602',
 '20000609',
 '20000616',
 '20000623',
 '20000630',
 '20000707',
 '20000714',
 '20000721',
 '20000728',
 '20000804',
 '20000811',
 '20000818',
 '20000825',
 '20000901',
 '20000908',
 '20000915',
 '20000922',
 '20000929',
 '20001013',
 '20001020',
 '20001027',
 '20001103',
 '20001110',
 '20001117',
 '20001124',
 '20001201',
 '20001208',
 '20001215',
 '20001222',
 '20001229',
 '20010105',
 '20010112',
 '20010119',
 '20010209',
 '20010216',
 '20010223',
 '20010302',
 '20010309',
 '20010316',
 '20010323',
 '20010330',
 '20010406',
 '20010413',
 '20010420',
 '20010427',
 '20010430',
 '20010511',
 '20010518',
 '20010525',
 '20010601',
 '20010608',
 '20010615',
 '20010622',
 '20010629',
 '20010706',
 '20010713',
 '20010720',
 '20010727',
 '20010803',
 '20010810',
 '20010817',
 '20010824',
 '20010831',
 '20010907',
 '20010914',
 '20010921',
 '20010928',
 '20011012',
 '20011019',
 '20011026',
 '20011102',
 '20011109',
 '20011116',
 '20011123',
 '20011130',
 '20011207',
 '20011214',
 '20011221',
 '20011228',
 '20020104',
 '20020111',
 '20020118',
 '20020125',
 '20020201',
 '20020208',
 '20020301',
 '20020308',
 '20020315',
 '20020322',
 '20020329',
 '20020405',
 '20020412',
 '20020419',
 '20020426',
 '20020430',
 '20020510',
 '20020517',
 '20020524',
 '20020531',
 '20020607',
 '20020614',
 '20020621',
 '20020628',
 '20020705',
 '20020712',
 '20020719',
 '20020726',
 '20020802',
 '20020809',
 '20020816',
 '20020823',
 '20020830',
 '20020906',
 '20020913',
 '20020920',
 '20020927',
 '20021011',
 '20021018',
 '20021025',
 '20021101',
 '20021108',
 '20021115',
 '20021122',
 '20021129',
 '20021206',
 '20021213',
 '20021220',
 '20021227',
 '20030103',
 '20030110',
 '20030117',
 '20030124',
 '20030129',
 '20030214',
 '20030221',
 '20030228',
 '20030307',
 '20030314',
 '20030321',
 '20030328',
 '20030404',
 '20030411',
 '20030418',
 '20030425',
 '20030430',
 '20030516',
 '20030523',
 '20030530',
 '20030606',
 '20030613',
 '20030620',
 '20030627',
 '20030704',
 '20030711',
 '20030718',
 '20030725',
 '20030801',
 '20030808',
 '20030815',
 '20030822',
 '20030829',
 '20030905',
 '20030912',
 '20030919',
 '20030926',
 '20030930',
 '20031010',
 '20031017',
 '20031024',
 '20031031',
 '20031107',
 '20031114',
 '20031121',
 '20031128',
 '20031205',
 '20031212',
 '20031219',
 '20031226',
 '20040102',
 '20040109',
 '20040116',
 '20040130',
 '20040206',
 '20040213',
 '20040220',
 '20040227',
 '20040305',
 '20040312',
 '20040319',
 '20040326',
 '20040402',
 '20040409',
 '20040416',
 '20040423',
 '20040430',
 '20040514',
 '20040521',
 '20040528',
 '20040604',
 '20040611',
 '20040618',
 '20040625',
 '20040702',
 '20040709',
 '20040716',
 '20040723',
 '20040730',
 '20040806',
 '20040813',
 '20040820',
 '20040827',
 '20040903',
 '20040910',
 '20040917',
 '20040924',
 '20040930',
 '20041008',
 '20041015',
 '20041022',
 '20041029',
 '20041105',
 '20041112',
 '20041119',
 '20041126',
 '20041203',
 '20041210',
 '20041217',
 '20041224',
 '20041231',
 '20050107',
 '20050114',
 '20050121',
 '20050128',
 '20050204',
 '20050218',
 '20050225',
 '20050304',
 '20050311',
 '20050318',
 '20050325',
 '20050401',
 '20050408',
 '20050415',
 '20050422',
 '20050429',
 '20050513',
 '20050520',
 '20050527',
 '20050603',
 '20050610',
 '20050617',
 '20050624',
 '20050701',
 '20050708',
 '20050715',
 '20050722',
 '20050729',
 '20050805',
 '20050812',
 '20050819',
 '20050826',
 '20050902',
 '20050909',
 '20050916',
 '20050923',
 '20050930',
 '20051014',
 '20051021',
 '20051028',
 '20051104',
 '20051111',
 '20051118',
 '20051125',
 '20051202',
 '20051209',
 '20051216',
 '20051223',
 '20051230',
 '20060106',
 '20060113',
 '20060120',
 '20060125',
 '20060210',
 '20060217',
 '20060224',
 '20060303',
 '20060310',
 '20060317',
 '20060324',
 '20060331',
 '20060407',
 '20060414',
 '20060421',
 '20060428',
 '20060512',
 '20060519',
 '20060526',
 '20060602',
 '20060609',
 '20060616',
 '20060623',
 '20060630',
 '20060707',
 '20060714',
 '20060721',
 '20060728',
 '20060804',
 '20060811',
 '20060818',
 '20060825',
 '20060901',
 '20060908',
 '20060915',
 '20060922',
 '20060929',
 '20061013',
 '20061020',
 '20061027',
 '20061103',
 '20061110',
 '20061117',
 '20061124',
 '20061201',
 '20061208',
 '20061215',
 '20061222',
 '20061229',
 '20070105',
 '20070112',
 '20070119',
 '20070126',
 '20070202',
 '20070209',
 '20070216',
 '20070302',
 '20070309',
 '20070316',
 '20070323',
 '20070330',
 '20070406',
 '20070413',
 '20070420',
 '20070427',
 '20070430',
 '20070511',
 '20070518',
 '20070525',
 '20070601',
 '20070608',
 '20070615',
 '20070622',
 '20070629',
 '20070706',
 '20070713',
 '20070720',
 '20070727',
 '20070803',
 '20070810',
 '20070817',
 '20070824',
 '20070831',
 '20070907',
 '20070914',
 '20070921',
 '20070928',
 '20071012',
 '20071019',
 '20071026',
 '20071102',
 '20071109',
 '20071116',
 '20071123',
 '20071130',
 '20071207',
 '20071214',
 '20071221',
 '20071228',
 '20080104',
 '20080111',
 '20080118',
 '20080125',
 '20080201',
 '20080205',
 '20080215',
 '20080222',
 '20080229',
 '20080307',
 '20080314',
 '20080321',
 '20080328',
 '20080403',
 '20080411',
 '20080418',
 '20080425',
 '20080430',
 '20080509',
 '20080516',
 '20080523',
 '20080530',
 '20080606',
 '20080613',
 '20080620',
 '20080627',
 '20080704',
 '20080711',
 '20080718',
 '20080725',
 '20080801',
 '20080808',
 '20080815',
 '20080822',
 '20080829',
 '20080905',
 '20080912',
 '20080919',
 '20080926',
 '20081010',
 '20081017',
 '20081024',
 '20081031',
 '20081107',
 '20081114',
 '20081121',
 '20081128',
 '20081205',
 '20081212',
 '20081219',
 '20081226',
 '20081231',
 '20090109',
 '20090116',
 '20090123',
 '20090206',
 '20090213',
 '20090220',
 '20090227',
 '20090306',
 '20090313',
 '20090320',
 '20090327',
 '20090403',
 '20090410',
 '20090417',
 '20090424',
 '20090430',
 '20090508',
 '20090515',
 '20090522',
 '20090527',
 '20090605',
 '20090612',
 '20090619',
 '20090626',
 '20090703',
 '20090710',
 '20090717',
 '20090724',
 '20090731',
 '20090807',
 '20090814',
 '20090821',
 '20090828',
 '20090904',
 '20090911',
 '20090918',
 '20090925',
 '20090930',
 '20091009',
 '20091016',
 '20091023',
 '20091030',
 '20091106',
 '20091113',
 '20091120',
 '20091127',
 '20091204',
 '20091211',
 '20091218',
 '20091225',
 '20091231',
 '20100108',
 '20100115',
 '20100122',
 '20100129',
 '20100205',
 '20100212',
 '20100226',
 '20100305',
 '20100312',
 '20100319',
 '20100326',
 '20100402',
 '20100409',
 '20100416',
 '20100423',
 '20100430',
 '20100507',
 '20100514',
 '20100521',
 '20100528',
 '20100604',
 '20100611',
 '20100618',
 '20100625',
 '20100702',
 '20100709',
 '20100716',
 '20100723',
 '20100730',
 '20100806',
 '20100813',
 '20100820',
 '20100827',
 '20100903',
 '20100910',
 '20100917',
 '20100921',
 '20100930',
 '20101008',
 '20101015',
 ...]

In [44]:
datetime.datetime.now()

datetime.datetime(2023, 4, 15, 18, 33, 22, 558392)