In [1]:
import tushare as ts
import pandas as pd
import datetime, time
import sqlite3
import sqlite_data
import time

In [2]:
pro = ts.pro_api()

In [52]:
from sqlite_data import DataApi
data_api = DataApi()

In [50]:
#获取单个公司高管全部数据
df1 = pro.daily_basic(ts_code='update_date_record')

In [51]:
df1

Empty DataFrame
Columns: [ts_code, trade_date, close, turnover_rate, turnover_rate_f, volume_ratio, pe, pe_ttm, pb, ps, ps_ttm, dv_ratio, dv_ttm, total_share, float_share, free_share, total_mv, circ_mv]
Index: []

In [63]:
cal_date = list(data_api.trade_cal(exchange='SSE',is_open='1')['cal_date'].unique())[::-1]

In [64]:
cal_date

['19901219',
 '19901220',
 '19901221',
 '19901224',
 '19901225',
 '19901226',
 '19901227',
 '19901228',
 '19901231',
 '19910102',
 '19910103',
 '19910104',
 '19910107',
 '19910108',
 '19910109',
 '19910110',
 '19910111',
 '19910114',
 '19910115',
 '19910116',
 '19910117',
 '19910118',
 '19910121',
 '19910122',
 '19910123',
 '19910124',
 '19910125',
 '19910128',
 '19910129',
 '19910130',
 '19910131',
 '19910201',
 '19910204',
 '19910205',
 '19910206',
 '19910207',
 '19910208',
 '19910211',
 '19910212',
 '19910213',
 '19910214',
 '19910219',
 '19910220',
 '19910221',
 '19910222',
 '19910225',
 '19910226',
 '19910227',
 '19910228',
 '19910301',
 '19910304',
 '19910305',
 '19910306',
 '19910307',
 '19910308',
 '19910311',
 '19910312',
 '19910313',
 '19910314',
 '19910315',
 '19910318',
 '19910319',
 '19910320',
 '19910321',
 '19910322',
 '19910325',
 '19910326',
 '19910327',
 '19910328',
 '19910329',
 '19910401',
 '19910402',
 '19910403',
 '19910404',
 '19910405',
 '19910408',
 '19910409',
 '19910410',
 '19910411',
 '19910412',
 '19910415',
 '19910416',
 '19910417',
 '19910418',
 '19910419',
 '19910422',
 '19910423',
 '19910424',
 '19910425',
 '19910426',
 '19910429',
 '19910430',
 '19910502',
 '19910503',
 '19910506',
 '19910507',
 '19910508',
 '19910509',
 '19910510',
 '19910513',
 '19910514',
 '19910515',
 '19910516',
 '19910517',
 '19910520',
 '19910521',
 '19910522',
 '19910523',
 '19910524',
 '19910527',
 '19910528',
 '19910529',
 '19910530',
 '19910531',
 '19910603',
 '19910604',
 '19910605',
 '19910606',
 '19910607',
 '19910610',
 '19910611',
 '19910612',
 '19910613',
 '19910614',
 '19910617',
 '19910618',
 '19910619',
 '19910620',
 '19910621',
 '19910624',
 '19910625',
 '19910626',
 '19910627',
 '19910628',
 '19910701',
 '19910702',
 '19910703',
 '19910704',
 '19910705',
 '19910708',
 '19910709',
 '19910710',
 '19910711',
 '19910712',
 '19910715',
 '19910716',
 '19910717',
 '19910718',
 '19910719',
 '19910722',
 '19910723',
 '19910724',
 '19910725',
 '19910726',
 '19910729',
 '19910730',
 '19910731',
 '19910801',
 '19910802',
 '19910805',
 '19910806',
 '19910807',
 '19910808',
 '19910809',
 '19910812',
 '19910813',
 '19910814',
 '19910815',
 '19910816',
 '19910819',
 '19910820',
 '19910821',
 '19910822',
 '19910823',
 '19910826',
 '19910827',
 '19910828',
 '19910829',
 '19910830',
 '19910902',
 '19910903',
 '19910904',
 '19910905',
 '19910906',
 '19910909',
 '19910910',
 '19910911',
 '19910912',
 '19910913',
 '19910916',
 '19910917',
 '19910918',
 '19910919',
 '19910920',
 '19910923',
 '19910924',
 '19910925',
 '19910926',
 '19910927',
 '19910930',
 '19911003',
 '19911004',
 '19911007',
 '19911008',
 '19911009',
 '19911010',
 '19911011',
 '19911014',
 '19911015',
 '19911016',
 '19911017',
 '19911018',
 '19911021',
 '19911022',
 '19911023',
 '19911024',
 '19911025',
 '19911028',
 '19911029',
 '19911030',
 '19911031',
 '19911101',
 '19911104',
 '19911105',
 '19911106',
 '19911107',
 '19911108',
 '19911111',
 '19911112',
 '19911113',
 '19911114',
 '19911115',
 '19911118',
 '19911119',
 '19911120',
 '19911121',
 '19911122',
 '19911125',
 '19911126',
 '19911127',
 '19911128',
 '19911129',
 '19911202',
 '19911203',
 '19911204',
 '19911205',
 '19911206',
 '19911209',
 '19911210',
 '19911211',
 '19911212',
 '19911213',
 '19911216',
 '19911217',
 '19911218',
 '19911219',
 '19911220',
 '19911223',
 '19911224',
 '19911225',
 '19911226',
 '19911227',
 '19911230',
 '19911231',
 '19920102',
 '19920103',
 '19920106',
 '19920107',
 '19920108',
 '19920109',
 '19920110',
 '19920113',
 '19920114',
 '19920115',
 '19920116',
 '19920117',
 '19920120',
 '19920121',
 '19920122',
 '19920123',
 '19920124',
 '19920127',
 '19920128',
 '19920129',
 '19920130',
 '19920131',
 '19920203',
 '19920207',
 '19920210',
 '19920211',
 '19920212',
 '19920213',
 '19920214',
 '19920217',
 '19920218',
 '19920219',
 '19920220',
 '19920221',
 '19920224',
 '19920225',
 '19920226',
 '19920227',
 '19920228',
 '19920302',
 '19920303',
 '19920304',
 '19920305',
 '19920306',
 '19920309',
 '19920310',
 '19920311',
 '19920312',
 '19920313',
 '19920316',
 '19920317',
 '19920318',
 '19920319',
 '19920320',
 '19920323',
 '19920324',
 '19920325',
 '19920326',
 '19920327',
 '19920330',
 '19920331',
 '19920401',
 '19920402',
 '19920403',
 '19920406',
 '19920407',
 '19920408',
 '19920409',
 '19920410',
 '19920413',
 '19920414',
 '19920415',
 '19920416',
 '19920417',
 '19920420',
 '19920421',
 '19920422',
 '19920423',
 '19920424',
 '19920427',
 '19920428',
 '19920429',
 '19920430',
 '19920504',
 '19920505',
 '19920506',
 '19920507',
 '19920508',
 '19920511',
 '19920512',
 '19920513',
 '19920514',
 '19920515',
 '19920518',
 '19920519',
 '19920520',
 '19920521',
 '19920522',
 '19920525',
 '19920526',
 '19920527',
 '19920528',
 '19920529',
 '19920601',
 '19920602',
 '19920603',
 '19920604',
 '19920605',
 '19920608',
 '19920609',
 '19920610',
 '19920611',
 '19920612',
 '19920615',
 '19920616',
 '19920617',
 '19920618',
 '19920619',
 '19920622',
 '19920623',
 '19920624',
 '19920625',
 '19920626',
 '19920629',
 '19920630',
 '19920701',
 '19920702',
 '19920703',
 '19920706',
 '19920707',
 '19920708',
 '19920709',
 '19920710',
 '19920713',
 '19920714',
 '19920715',
 '19920716',
 '19920717',
 '19920720',
 '19920721',
 '19920722',
 '19920723',
 '19920724',
 '19920727',
 '19920728',
 '19920729',
 '19920730',
 '19920731',
 '19920803',
 '19920804',
 '19920805',
 '19920806',
 '19920807',
 '19920810',
 '19920811',
 '19920812',
 '19920813',
 '19920814',
 '19920817',
 '19920818',
 '19920819',
 '19920820',
 '19920821',
 '19920824',
 '19920825',
 '19920826',
 '19920827',
 '19920828',
 '19920831',
 '19920901',
 '19920902',
 '19920903',
 '19920904',
 '19920907',
 '19920908',
 '19920909',
 '19920910',
 '19920911',
 '19920914',
 '19920915',
 '19920916',
 '19920917',
 '19920918',
 '19920921',
 '19920922',
 '19920923',
 '19920924',
 '19920925',
 '19920928',
 '19920929',
 '19920930',
 '19921005',
 '19921006',
 '19921007',
 '19921008',
 '19921009',
 '19921012',
 '19921013',
 '19921014',
 '19921015',
 '19921016',
 '19921019',
 '19921020',
 '19921021',
 '19921022',
 '19921023',
 '19921026',
 '19921027',
 '19921028',
 '19921029',
 '19921030',
 '19921102',
 '19921103',
 '19921104',
 '19921105',
 '19921106',
 '19921109',
 '19921110',
 '19921111',
 '19921112',
 '19921113',
 '19921116',
 '19921117',
 '19921118',
 '19921119',
 '19921120',
 '19921123',
 '19921124',
 '19921125',
 '19921126',
 '19921127',
 '19921130',
 '19921201',
 '19921202',
 '19921203',
 '19921204',
 '19921207',
 '19921208',
 '19921209',
 '19921210',
 '19921211',
 '19921214',
 '19921215',
 '19921216',
 '19921217',
 '19921218',
 '19921221',
 '19921222',
 '19921223',
 '19921224',
 '19921225',
 '19921228',
 '19921229',
 '19921230',
 '19921231',
 '19930104',
 '19930105',
 '19930106',
 '19930107',
 '19930108',
 '19930111',
 '19930112',
 '19930113',
 '19930114',
 '19930115',
 '19930118',
 '19930119',
 '19930120',
 '19930121',
 '19930122',
 '19930127',
 '19930128',
 '19930129',
 '19930201',
 '19930202',
 '19930203',
 '19930204',
 '19930205',
 '19930208',
 '19930209',
 '19930210',
 '19930211',
 '19930212',
 '19930215',
 '19930216',
 '19930217',
 '19930218',
 '19930219',
 '19930222',
 '19930223',
 '19930224',
 '19930225',
 '19930226',
 '19930301',
 '19930302',
 '19930303',
 '19930304',
 '19930305',
 '19930308',
 '19930309',
 '19930310',
 '19930311',
 '19930312',
 '19930315',
 '19930316',
 '19930317',
 '19930318',
 '19930319',
 '19930322',
 '19930323',
 '19930324',
 '19930325',
 '19930326',
 '19930329',
 '19930330',
 '19930331',
 '19930401',
 '19930402',
 '19930405',
 '19930406',
 '19930407',
 '19930408',
 '19930409',
 '19930412',
 '19930413',
 '19930414',
 '19930415',
 '19930416',
 '19930419',
 '19930420',
 '19930421',
 '19930422',
 '19930423',
 '19930426',
 '19930427',
 '19930428',
 '19930429',
 '19930430',
 '19930503',
 '19930504',
 '19930505',
 '19930506',
 '19930507',
 '19930510',
 '19930511',
 '19930512',
 '19930513',
 '19930514',
 '19930517',
 '19930518',
 '19930519',
 '19930520',
 '19930521',
 '19930524',
 '19930525',
 '19930526',
 '19930527',
 '19930528',
 '19930531',
 '19930601',
 '19930602',
 '19930603',
 '19930604',
 '19930607',
 '19930608',
 '19930609',
 '19930610',
 '19930611',
 '19930614',
 '19930615',
 '19930616',
 '19930617',
 '19930618',
 '19930621',
 '19930622',
 '19930623',
 '19930624',
 '19930625',
 '19930628',
 '19930629',
 '19930630',
 '19930701',
 '19930702',
 '19930705',
 '19930706',
 '19930707',
 '19930708',
 '19930709',
 '19930712',
 '19930713',
 '19930714',
 '19930715',
 '19930716',
 '19930719',
 '19930720',
 '19930721',
 '19930722',
 '19930723',
 '19930726',
 '19930727',
 '19930728',
 '19930729',
 '19930730',
 '19930802',
 '19930803',
 '19930804',
 '19930805',
 '19930806',
 '19930809',
 '19930810',
 '19930811',
 '19930812',
 '19930813',
 '19930816',
 '19930817',
 '19930818',
 '19930819',
 '19930820',
 '19930823',
 '19930824',
 '19930825',
 '19930826',
 '19930827',
 '19930830',
 '19930831',
 '19930901',
 '19930902',
 '19930903',
 '19930906',
 '19930907',
 '19930908',
 '19930909',
 '19930910',
 '19930913',
 '19930914',
 '19930915',
 '19930916',
 '19930917',
 '19930920',
 '19930921',
 '19930922',
 '19930923',
 '19930924',
 '19930927',
 '19930928',
 '19930929',
 '19930930',
 '19931004',
 '19931005',
 '19931006',
 '19931007',
 '19931008',
 '19931011',
 '19931012',
 '19931013',
 '19931014',
 '19931015',
 '19931018',
 '19931019',
 '19931020',
 '19931021',
 '19931022',
 '19931025',
 '19931026',
 '19931027',
 '19931028',
 '19931029',
 '19931101',
 '19931102',
 '19931103',
 '19931104',
 '19931105',
 '19931108',
 '19931109',
 '19931110',
 '19931111',
 '19931112',
 '19931115',
 '19931116',
 '19931117',
 '19931118',
 '19931119',
 '19931122',
 '19931123',
 '19931124',
 '19931125',
 '19931126',
 '19931129',
 '19931130',
 '19931201',
 '19931202',
 '19931203',
 '19931206',
 '19931207',
 '19931208',
 '19931209',
 '19931210',
 '19931213',
 '19931214',
 '19931215',
 '19931216',
 '19931217',
 '19931220',
 '19931221',
 '19931222',
 '19931223',
 '19931224',
 '19931227',
 '19931228',
 '19931229',
 '19931230',
 '19931231',
 '19940103',
 '19940104',
 '19940105',
 '19940106',
 '19940107',
 '19940110',
 '19940111',
 '19940112',
 '19940113',
 '19940114',
 '19940117',
 '19940118',
 '19940119',
 '19940120',
 '19940121',
 '19940124',
 '19940125',
 '19940126',
 '19940127',
 '19940128',
 '19940131',
 '19940201',
 '19940202',
 '19940203',
 '19940204',
 '19940214',
 '19940215',
 '19940216',
 '19940217',
 '19940218',
 '19940221',
 '19940222',
 '19940223',
 '19940224',
 '19940225',
 '19940228',
 '19940301',
 '19940302',
 '19940303',
 '19940304',
 '19940307',
 '19940308',
 '19940309',
 '19940310',
 '19940311',
 '19940314',
 '19940315',
 '19940316',
 '19940317',
 '19940318',
 '19940321',
 '19940322',
 '19940323',
 '19940324',
 '19940325',
 '19940328',
 '19940329',
 '19940330',
 '19940331',
 '19940401',
 '19940404',
 '19940405',
 '19940406',
 '19940407',
 '19940408',
 '19940411',
 '19940412',
 '19940413',
 '19940414',
 '19940415',
 '19940418',
 '19940419',
 '19940420',
 '19940421',
 '19940422',
 '19940425',
 '19940426',
 '19940427',
 '19940428',
 '19940429',
 '19940503',
 '19940504',
 '19940505',
 '19940506',
 '19940509',
 '19940510',
 '19940511',
 '19940512',
 '19940513',
 '19940516',
 '19940517',
 '19940518',
 '19940519',
 '19940520',
 '19940523',
 '19940524',
 '19940525',
 '19940526',
 '19940527',
 '19940530',
 '19940531',
 '19940601',
 '19940602',
 '19940603',
 '19940606',
 '19940607',
 '19940608',
 '19940609',
 '19940610',
 '19940613',
 '19940614',
 '19940615',
 '19940616',
 '19940617',
 '19940620',
 '19940621',
 '19940622',
 '19940623',
 '19940624',
 '19940627',
 '19940628',
 '19940629',
 '19940630',
 '19940701',
 '19940704',
 '19940705',
 '19940706',
 '19940707',
 '19940708',
 '19940711',
 '19940712',
 '19940713',
 '19940714',
 '19940715',
 '19940718',
 '19940719',
 '19940720',
 '19940721',
 '19940722',
 '19940725',
 '19940726',
 '19940727',
 '19940728',
 '19940729',
 '19940801',
 '19940802',
 '19940803',
 '19940804',
 '19940805',
 '19940808',
 '19940809',
 '19940810',
 '19940811',
 '19940812',
 '19940815',
 '19940816',
 '19940817',
 '19940818',
 '19940819',
 '19940822',
 '19940823',
 '19940824',
 '19940825',
 '19940826',
 '19940829',
 '19940830',
 '19940831',
 '19940901',
 '19940902',
 '19940905',
 '19940906',
 '19940907',
 '19940908',
 '19940909',
 '19940912',
 '19940913',
 '19940914',
 '19940915',
 '19940916',
 '19940919',
 '19940920',
 '19940921',
 '19940922',
 '19940923',
 '19940926',
 '19940927',
 '19940928',
 '19940929',
 '19940930',
 '19941005',
 '19941006',
 '19941007',
 '19941010',
 '19941011',
 '19941012',
 '19941013',
 '19941014',
 '19941017',
 '19941018',
 '19941019',
 '19941020',
 '19941021',
 '19941024',
 '19941025',
 '19941026',
 '19941027',
 '19941028',
 '19941031',
 '19941101',
 '19941102',
 '19941103',
 '19941104',
 '19941107',
 '19941108',
 '19941109',
 '19941110',
 '19941111',
 '19941114',
 '19941115',
 '19941116',
 '19941117',
 '19941118',
 '19941121',
 '19941122',
 ...]

In [ ]:
date_list = cal_date[0:cal_date.index('20160624')]

In [40]:
df2 = pd.DataFrame({'trade_date':date_list})
df2['ts_code'] = 'update_date_record'
df2['close'] = 0
df2['ts_code_trade_date'] = df.apply(lambda x: x['ts_code'] + str(x['trade_date']), axis=1)

In [41]:
df = pd.concat([df1[0:1], df2], axis=0)[1:]

In [48]:
df

,ts_code,trade_date,close,turnover_rate,turnover_rate_f,volume_ratio,pe,pe_ttm,pb,ps,ps_ttm,dv_ratio,dv_ttm,total_share,float_share,free_share,total_mv,circ_mv,ts_code_trade_date
0,update_date_record,19901219,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,update_date_record19901219
1,update_date_record,19901220,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,update_date_record19901220
2,update_date_record,19901221,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,update_date_record19901221
3,update_date_record,19901224,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,update_date_record19901224
4,update_date_record,19901225,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,update_date_record19901225
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6235,update_date_record,20160617,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,update_date_record20160617
6236,update_date_record,20160620,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,update_date_record20160620
6237,update_date_record,20160621,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,update_date_record20160621
6238,update_date_record,20160622,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,update_date_record20160622
6239,update_date_record,20160623,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,update_date_record20160623

In [8]:
df['ts_code_trade_date'] = df.apply(lambda x: x['ts_code'] + str(x['trade_date']), axis=1)

In [49]:
sqlite_data.write(df, 'daily_basic')

IntegrityError: UNIQUE constraint failed: daily_basic.ts_code_trade_date

In [57]:
daily_basic = data_api.daily_basic(ts_code='update_date_record', fields=['trade_date'])

In [60]:
daily_basic['trade_date'][daily_basic.index[-1]]

'20160623'

In [22]:
# sqlite_data.write(df,'fx_obasic')

In [62]:
data_api.daily_basic(trade_date='20180912')

,ts_code_trade_date,ts_code,trade_date,close,turnover_rate,turnover_rate_f,volume_ratio,pe,pe_ttm,pb,ps,ps_ttm,dv_ratio,dv_ttm,total_share,float_share,free_share,total_mv,circ_mv
0,600230.SH20180912,600230.SH,20180912,22.11,0.5409,1.0062,0.62,7.0974,6.5277,2.7005,2.0616,1.8808,0.4200,1.6153,41186.3502,41186.3502,22139.6078,9.106302e+05,9.106302e+05
1,600237.SH20180912,600237.SH,20180912,3.65,0.3829,0.4599,0.71,146.7054,158.5235,1.6603,2.5326,2.3885,0.0000,NaN,56436.9565,56436.9565,46980.8285,2.059949e+05,2.059949e+05
2,002465.SZ20180912,002465.SZ,20180912,8.95,1.4381,2.0097,1.05,70.3998,60.3203,2.5224,6.1595,5.8783,1.0392,0.8940,230694.3384,207050.8115,148158.2821,2.064714e+06,1.853105e+06
3,600007.SH20180912,600007.SH,20180912,14.80,0.0821,0.4243,0.61,23.4840,20.0452,2.2763,5.3888,4.8661,2.0270,2.1622,100728.2534,100728.2534,19492.2293,1.490778e+06,1.490778e+06
4,300068.SZ20180912,300068.SZ,20180912,12.08,0.9097,1.3042,0.60,27.8305,20.1496,1.7089,1.2273,1.1716,1.4852,1.6507,87750.5321,59994.1120,41847.5391,1.060026e+06,7.247289e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3438,300359.SZ20180912,300359.SZ,20180912,7.40,1.7684,2.3537,0.45,70.7468,55.5497,2.3203,4.5484,5.2997,0.3514,0.2703,63377.2477,41655.2917,31296.8034,4.689916e+05,3.082492e+05
3439,002853.SZ20180912,002853.SZ,20180912,17.22,0.6775,0.6775,0.60,25.9748,22.8975,2.8623,3.2366,2.8012,0.6969,0.9292,15534.1500,5803.0745,5803.0745,2.674981e+05,9.992894e+04
3440,001872.SZ20180912,001872.SZ,20180912,17.73,0.2968,1.4683,0.62,22.6596,21.0084,2.5493,4.6542,4.1229,2.7975,7.4394,64476.3730,46485.9300,9398.1300,1.143166e+06,8.241955e+05
3441,001914.SZ20180912,001914.SZ,20180912,6.70,0.2565,0.5267,1.43,29.6747,10.7173,1.0536,0.7582,0.7084,1.0448,1.4925,66696.1416,66681.9666,32479.0786,4.468641e+05,4.467692e+05
3442,update_date_record20180912,update_date_record,20180912,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN